// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrtBackEnd.DatabaseContext;

#nullable disable

namespace OrtBackEnd.Migrations
{
    [DbContext(typeof(TestsDb))]
    [Migration("20240205195340_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrtBackEnd.Models.Tests", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("AnswerA")
                        .HasColumnType("text");

                    b.Property<string>("AnswerB")
                        .HasColumnType("text");

                    b.Property<string>("AnswerC")
                        .HasColumnType("text");

                    b.Property<string>("AnswerD")
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            AnswerA = "",
                            AnswerB = "",
                            AnswerC = "",
                            AnswerD = "",
                            CorrectAnswer = "",
                            QuestionText = ""
                        },
                        new
                        {
                            QuestionId = 2,
                            AnswerA = "",
                            AnswerB = "",
                            AnswerC = "",
                            AnswerD = "",
                            CorrectAnswer = "",
                            QuestionText = ""
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerA = "",
                            AnswerB = "",
                            AnswerC = "",
                            AnswerD = "",
                            CorrectAnswer = "",
                            QuestionText = ""
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerA = "",
                            AnswerB = "",
                            AnswerC = "",
                            AnswerD = "",
                            CorrectAnswer = "",
                            QuestionText = ""
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerA = "",
                            AnswerB = "",
                            AnswerC = "",
                            AnswerD = "",
                            CorrectAnswer = "",
                            QuestionText = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
