// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrtBackEnd.DatabaseContext;

#nullable disable

namespace OrtBackEnd.Migrations
{
    [DbContext(typeof(TestsDb))]
    [Migration("20240205221401_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrtBackEnd.Models.Tests", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("AnswerA")
                        .HasColumnType("text");

                    b.Property<string>("AnswerB")
                        .HasColumnType("text");

                    b.Property<string>("AnswerC")
                        .HasColumnType("text");

                    b.Property<string>("AnswerD")
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("text");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            AnswerA = "readable",
                            AnswerB = "content",
                            AnswerC = "making",
                            AnswerD = "web page",
                            CorrectAnswer = "content",
                            QuestionText = "Lorem Ipsum is simply dummy text of the printing?"
                        },
                        new
                        {
                            QuestionId = 2,
                            AnswerA = "middle",
                            AnswerB = "Hampden-Sydney",
                            AnswerC = "undoubtable",
                            AnswerD = "reproduced",
                            CorrectAnswer = "middle",
                            QuestionText = "There are many variations of passages of Lorem Ipsum available"
                        },
                        new
                        {
                            QuestionId = 3,
                            AnswerA = "generate",
                            AnswerB = "Ipsum",
                            AnswerC = "therefore",
                            AnswerD = "repetition",
                            CorrectAnswer = "Ipsum",
                            QuestionText = "All the Lorem Ipsum generators on the Internet tend to repeat predefined"
                        },
                        new
                        {
                            QuestionId = 4,
                            AnswerA = "reproduced",
                            AnswerB = "exact",
                            AnswerC = "accompanied",
                            AnswerD = "versions",
                            CorrectAnswer = "versions",
                            QuestionText = "The standard chunk of Lorem Ipsum used since the"
                        },
                        new
                        {
                            QuestionId = 5,
                            AnswerA = "words",
                            AnswerB = "standard",
                            AnswerC = "popular",
                            AnswerD = "repeat",
                            CorrectAnswer = "generate",
                            QuestionText = "Lorem Ipsum comes from sections 1.10.32 and 1.10.33"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
